### PR TITLE
Fixed usage pause_short() on xScope host application 

### PR DESCRIPTION
**Pull request by lucianomartin**
- set variables as volatile
- used pause_short() for all the platforms 
- updated CHANGELOG and module_build_info

### CODE REVIEW

**Comment by larry-xmos** [comment]
Thanks

This is continuation of #41 and #42. It looks like across those three pull requests the only change against 3.2.0rc5 is adding a pause_short to the version query.

I'd like to spot check that this works on Mac please before merging

Also, since this will be done post release, we'll need to increment version number and add a note in changelog

**Comment by larry-xmos** [comment]
For completeness, could you resolve bug 17871 please and link to this pull request. That bugzilla will be referenced by VocalFusion readme so we'll want to be able to track down the fix.

**Comment by xross** [comment]
As of commit https://github.com/xmos/lib_device_control/commit/999b868a197415fcd221929b618c2e2a7d2adb49

pause_short is 

void pause_short(void)
{
  Sleep(0);
}

For _WIN32 and !WIN32

**Comment by larry-xmos** [comment]
Luciano, in Bugzilla could you please set bug 17871 to RESOLVED MOVED and post a comment with URL to this pull request

**Comment by larry-xmos** [comment]
Thanks, that looks good to go

**Pull request merged**
